# macOS-specific packages via Homebrew
# Note: Cross-platform CLI tools (starship, zoxide, eza, bat, ripgrep) are in Cargofile

tap "opencode-ai/tap"
brew "cmake"
brew "cocoapods"
brew "codex"
brew "coreutils"
brew "defaultbrowser"
brew "docker"
brew "dprint"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "gitleaks"
brew "glow"
brew "httpie"
brew "huggingface-cli"
brew "llm"
brew "python@3.12"
brew "ncdu"
brew "utf8proc"
brew "neovim"
brew "node"
brew "openai-whisper"
brew "pandoc"
brew "pipx"
brew "pkgconf"
brew "pyenv"
brew "zellij"
brew "zola"
brew "opencode-ai/tap/opencode"
cask "alacritty"
cask "devtoys"
cask "maccy"
cask "xquartz"
